# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
enable-beta-ecosystems: true
updates:
  # Enable version updates for uv
  - package-ecosystem: "uv"
    # Look for `pyproject.toml` and `uv.lock` files in the `root` directory
    directory: "/"
    # Check the pypi registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    groups:
      # Non nomad dependencies
      not-nomad-dependencies:
        exclude-patterns:
          - "nomad*"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
