services:
  postgresql:
    container_name: nomad_oasis_postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:16

  temporal:
    container_name: nomad_oasis_temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/auto-setup:1.27.2
    healthcheck:
      test: >
        bash -c '
          temporal operator cluster health --address $$(hostname -i):7233 |
          grep -q "SERVING"
        '
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  temporal-ui:
    container_name: nomad_oasis_temporal_ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
      - TEMPORAL_AUTH_LABEL=fairdi_nomad_test
      - TEMPORAL_AUTH_CLIENT_SECRET="test"
      - TEMPORAL_AUTH_CALLBACK_URL=http://localhost:4173/auth/sso/callback
      - TEMPORAL_AUTH_ENABLED=true
      - TEMPORAL_AUTH_TYPE=oidc
      - TEMPORAL_AUTH_PROVIDER_URL=https://nomad-lab.eu/fairdi/keycloak/auth/realms/fairdi_nomad_test
      - TEMPORAL_AUTH_ISSUER_URL=https://nomad-lab.eu/fairdi/keycloak/auth/realms/fairdi_nomad_test
      - TEMPORAL_AUTH_CLIENT_ID=nomad_public
      - TEMPORAL_AUTH_SCOPES=openid,email,profile
    image: temporalio/ui:2.34.0
    ports:
      - "4173:8080"

  keycloak:
    image: gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-test-keycloak:v1.0
    platform: linux/amd64
    container_name: keycloak
    environment:
      # clashes with imported admin user in master realm
      # - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      # - KC_BOOTSTRAP_ADMIN_PASSWORD=password
      - KC_LOG_LEVEL=info
      - KC_HOSTNAME_DEBUG=true
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
    command:
      - start-dev
      - --import-realm
      - --verbose
    ports:
      - 8080:8080
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
      test: bash /opt/keycloak/bin/healthcheck_keycloak.sh || exit 1
