services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: true

plugins:
  entry_points:
    options:
      nomad_north_jupyter.north_tools:jupyter:
        north_tool:
          image: ghcr.io/fairmat-nfdi/nomad-north-jupyter:latest

meta:
  deployment: "oasis"
  deployment_url: "https://my-oasis.org/api"
  maintainer_email: "me@my-oasis.org"

logstash:
  enabled: false

temporal:
  enabled: true

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1

north:
  enabled: true
  enable_new_hub_api: true
  hub_ip: localhost
  docker_network: nomad_oasis_network
  tools:
    options:
      pyiron:
        display_name: Pyiron
        description: '### **Pyiron**: Complex workflows made easy

          From rapid prototyping to high performance computing in materials science.
          [Homepage](https://pyiron.org/).'
        external_mounts: [ ]
        file_extensions:
          - ipynb
        icon: logo/pyiron.png
        image: pyiron/pyiron:latest
        image_pull_policy: Always
        default_url: /lab
        maintainer:
          - email: markus.scheidgen@physik.hu-berlin.de
            name: Markus Scheidgen
        mount_path: /home/jovyan
        path_prefix: lab/tree
        privileged: false
        short_description: Jupyterlab with pyiron installed.
        with_path: true
      nionswift:
        display_name: Nion Swift
        description: '### **Nion Swift**:

          Nion Swift is a software package for electron microscopy data
          analysis and visualization. It is designed to be easy to use and to provide
          a high degree of interactivity. [Homepage](https://nionswift.readthedocs.io/en/stable/).'
        icon: logo/nionswift.png
        external_mounts: [ ]
        file_extensions:
          - tiff
          - tif
          - dm3
          - dm4
          - hdf5
          - h5
          - nion
        image: gitlab-registry.mpcdf.mpg.de/nomad-lab/north/nionswift:refactor
        image_pull_policy: Always
        default_url: /desktop
        maintainer:
          - email: sherjeel.shabih@hu-berlin.de
            name: Sherjeel Shabih
        mount_path: /home/jovyan
        privileged: false
        short_description: Run Nion Swift to analyze data as well as prepare focus
          series reconstructions in NOMAD.
        with_path: false
      nexustools:
        display_name: NeXus
        description: '### **NeXus**:

          Includes multiple NeXus tools for visualization and analysis.'
        external_mounts: [ ]
        file_extensions:
          - nxs
          - nx
          - nexus
          - hdf5
          - hd5
          - h5
          - hdf
          - ipynb
        icon: logo/nexus.png
        image: gitlab-registry.mpcdf.mpg.de/nomad-lab/north/nexus:weptop-replacement
        image_pull_policy: Always
        default_url: /lab
        maintainer:
          - email: sandor.brockhauser@physik.hu-berlin.de
            name: Sandor Brockhauser
        mount_path: /home/jovyan
        privileged: false
        short_description: Analyse your NeXus files in NOMAD with several NeXus-compatible tools.
        with_path: true
      fiji:
        display_name: FIJI
        description: '### **FIJI** (Fiji Is Just ImageJ): Image processing package

          It can be used for tasks such as image editing, image analysis,
          and image processing. [Homepage](https://fiji.sc/).'
        external_mounts: [ ]
        file_extensions:
          - tif
          - tiff
          - jpeg
          - png
          - gif
          - bmp
          - avi
        icon: logo/fiji.png
        image: gitlab-registry.mpcdf.mpg.de/nomad-lab/north/fiji:weptop-replacement
        image_pull_policy: Always
        default_url: /desktop
        maintainer:
          - email: markus.kuehbach@physik.hu-berlin.de
            name: "Markus K\xFChbach"
        mount_path: /home/jovyan
        privileged: false
        short_description: Use FIJI to analyze and visualize your images in your NOMAD files.
        with_path: false
      vesta:
        display_name: VESTA
        description: '### **VESTA**: Visualization for Electronic and STructural Analysis

          VESTA is a software program used for visualizing and analyzing crystal structures,
          electron density maps, and other three-dimensional data related to materials
          science and crystallography. [Homepage](http://jp-minerals.org/vesta/en/).'
        external_mounts: [ ]
        file_extensions:
          - vesta
          - cif
          - res
          - vasp
          - xyz
          - pdb
          - mcif
          - fsf
          - fcf
          - shelx
          - stl
          - cgo
          - wrl
          - pov
          - spf
        icon: logo/vesta.png
        image: gitlab-registry.mpcdf.mpg.de/nomad-lab/north/abtem:refactor
        image_pull_policy: Always
        default_url: /desktop
        maintainer:
          - email: markus.kuehbach@physik.hu-berlin.de
            name: "Markus K\xFChbach"
        mount_path: /home/jovyan
        privileged: false
        short_description: Run VESTA to analyse and visualize your crystal structures in
          your NOMAD files.
        with_path: false
      abtem:
        display_name: abTEM
        description: '### **abTEM, GPAW and VESTA**:

          VESTA, GPAW, and abTEM configured in one container for simulating
          images and diffraction patterns in transmission electron microscopy.'
        external_mounts: [ ]
        file_extensions:
          - ipynb
        icon: logo/abtem.png
        image: gitlab-registry.mpcdf.mpg.de/nomad-lab/north/abtem:refactor
        image_pull_policy: Always
        default_url: /lab
        maintainer:
          - email: markus.kuehbach@physik.hu-berlin.de
            name: "Markus K\xFChbach"
        mount_path: /home/jovyan
        privileged: false
        short_description: Electronic structure supported image simulation for transmission
          electron microscopy.
        with_path: true
      ellips:
        display_name: Ellipsometry
        description: '### **Ellipsometry**:

          This example presents the capabilities of the NOMAD platform
          to store and standardize ellipsometry data. It shows the generation of a
          NeXus file according to the [NXellipsometry](https://manual.nexusformat.org/classes/contributed_definitions/NXellipsometry.html#nxellipsometry)
          application definition and a successive analysis of a SiO2 on Si Psi/Delta
          measurement.'
        external_mounts: [ ]
        file_extensions:
          - ipynb
          - nxs
        icon: logo/jupyter.svg
        image: gitlab-registry.mpcdf.mpg.de/nomad-lab/north/ellips:refactor
        image_pull_policy: Always
        default_url: /lab
        maintainer:
          - email: sandor.brockhauser@physik.hu-berlin.de
            name: Sandor Brockhauser
        mount_path: /home/jovyan
        path_prefix: lab/tree
        privileged: false
        short_description: An example for analyzing ellipsometric data.
        with_path: true
      xps:
        display_name: XPES
        description: '### **XPES**: X-ray Photoelectron Spectroscopy

          Includes tools for analyzing X-ray Photoelectron Spectroscopy
          (XPS) spectra and converting SPECS SLE files into NeXus.'
        external_mounts: [ ]
        file_extensions:
          - ipynb
          - nxs
          - h5
          - hdf5
        icon: logo/jupyter.svg
        image: gitlab-registry.mpcdf.mpg.de/nomad-lab/north/xps:master
        default_url: /lab
        image_pull_policy: Always
        maintainer:
          - email: lukas.pielsticker@physik.hu-berlin.de
            name: Lukas Pielsticker
        mount_path: /home/jovyan
        path_prefix: lab/tree
        privileged: false
        short_description: An example for analyzing XPS data.
        with_path: true
      spm:
        display_name: SPM
        description: '### **SPM**: Scanning Probe Microscopy

          This tool provides three example experiments from Scanning Probe Microscopy:
          Scanning Tunneling Spectroscopy (STS), Scanning Tunneling Microscopy (STM),
          and Atomic Force Microscopy (AFM).

          In the provided examples, the corresponding Jupyter notebooks contain code
          that transforms raw data generated by the Nanonis software into the NeXus file
          format, following the application definitions NXsts, NXstm, and NXafm.'
        external_mounts: []
        file_extensions:
          - ipynb
          - nxs
          - h5
          - hdf5
        icon: logo/jupyter.svg
        image: gitlab-registry.mpcdf.mpg.de/nomad-lab/north/spm:main
        image_pull_policy: Always
        default_url: /lab
        maintainer:
          - email: rubel.mozumder@physik.hu-berlin.de
            name: Rubel Mozumder
        mount_path: /home/jovyan
        path_prefix: lab/tree
        privileged: false
        short_description: An example for analyzing SPM (STS / STM / AFM) experiment.
        with_path: true
      apmtools:
        display_name: APM tools
        description: '### **APM tools**: Atom Probe Microscopy tools

          Miscellaneous tools from the atom probe community:

          Currently APTyzer, paraprobe-toolbox, and APAV'
        external_mounts: [ ]
        file_extensions:
          - ipynb
        icon: logo/jupyter.svg
        image: gitlab-registry.mpcdf.mpg.de/nomad-lab/north/apmtools:refactor
        image_pull_policy: Always
        default_url: /lab
        maintainer:
          - email: markus.kuehbach@physik.hu-berlin.de
            name: "Markus K\xFChbach"
        mount_path: /home/jovyan
        privileged: false
        short_description: An example for analyzing atom probe data.
        with_path: true
